"""Add user model with authentication

Revision ID: 1918d83352a6
Revises: 
Create Date: 2025-11-12 20:00:08.646966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1918d83352a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='Unique username for login'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='User email address'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Hashed password'),
    sa.Column('full_name', sa.String(length=100), nullable=True, comment="User's full display name"),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'MANAGER', 'DEVELOPER', 'VIEWER', name='userrole'), nullable=False, comment='User role for access control'),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False, comment='Whether email address is verified'),
    sa.Column('email_verification_token', sa.String(length=255), nullable=True, comment='Token for email verification'),
    sa.Column('email_verification_expires', sa.DateTime(timezone=True), nullable=True, comment='Email verification token expiration'),
    sa.Column('password_reset_token', sa.String(length=255), nullable=True, comment='Token for password reset'),
    sa.Column('password_reset_expires', sa.DateTime(timezone=True), nullable=True, comment='Password reset token expiration'),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Last password change timestamp'),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False, comment='Number of consecutive failed login attempts'),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True, comment='Account locked until this timestamp'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='Last successful login timestamp'),
    sa.Column('last_login_ip', sa.String(length=45), nullable=True, comment='IP address of last login'),
    sa.Column('avatar_url', sa.String(length=500), nullable=True, comment='URL to user avatar image'),
    sa.Column('bio', sa.Text(), nullable=True, comment='User biography/description'),
    sa.Column('timezone', sa.String(length=50), nullable=False, comment="User's preferred timezone"),
    sa.Column('language', sa.String(length=10), nullable=False, comment="User's preferred language (ISO 639-1)"),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record creation timestamp'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='Record last update timestamp'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Record deletion timestamp (NULL means not deleted)'),
    sa.Column('is_deleted', sa.Boolean(), nullable=False, comment='Soft delete flag'),
    sa.Column('created_by_id', sa.Integer(), nullable=True, comment='ID of user who created this record'),
    sa.Column('updated_by_id', sa.Integer(), nullable=True, comment='ID of user who last updated this record'),
    sa.Column('deleted_by_id', sa.Integer(), nullable=True, comment='ID of user who deleted this record'),
    sa.Column('metadata_json', sa.Text(), nullable=True, comment='Additional metadata stored as JSON'),
    sa.Column('status', sa.String(length=50), nullable=False, comment='Entity status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
